test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,9 +19,9 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-    #   # Set up Docker Buildx for cross-platform builds
-    #   - name: Set up Docker Buildx
-    #     uses: docker/setup-buildx-action@v3
+      # Set up Docker Buildx for cross-platform builds
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
       # Log in to Docker Hub
       - name: Log in to Docker Hub
@@ -44,6 +44,11 @@ jobs:
           echo "IMAGE_NAME_LATEST=08050481076/joktan4194:latest"
           echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
           echo "IMAGE_NAME_LATEST=${IMAGE_NAME_LATEST}" >> $GITHUB_ENV
+
+      - name: Check Dockerfile
+        run: |
+            if [ ! -f ./Dockerfile ]; then echo "Dockerfile not found!"; exit 1; fi
+        
 
       # Build the Docker image
       - name: Build Docker image
